DROP TABLE IF EXISTS DOMICILIOS;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50),
NUMERO INT,
LOCALIDAD VARCHAR(50),
PROVINCIA VARCHAR(50)
);

DROP TABLE IF EXISTS PACIENTES;

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50),
NOMBRE VARCHAR(50),
EMAIL VARCHAR(32),
DNI VARCHAR(12),
FECHA_INGRESO DATE,
DOMICILIO_ID INT,
ODONTOLOGO_ID INT
);

DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50),
NOMBRE VARCHAR(50),
MATRICULA VARCHAR(50)
);

DROP TABLE IF EXISTS TURNOS;

CREATE TABLE TURNOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
PACIENTE_ID INT,
ODONTOLOGO_ID INT,
FECHA_HORA DATE
);


INSERT INTO DOMICILIOS(CALLE,NUMERO,LOCALIDAD,PROVINCIA) VALUES('Av Santa fe',444,'CABA','Buenos Aires');
INSERT INTO DOMICILIOS(CALLE,NUMERO,LOCALIDAD,PROVINCIA) VALUES('Av Avellaneda',333,'CABA','Buenos Aires');

INSERT INTO PACIENTES(APELLIDO,NOMBRE,EMAIL,DNI,FECHA_INGRESO,DOMICILIO_ID,ODONTOLOGO_ID) VALUES('Paz','Santiago','santi@gmail.com','88888888','2018-05-08',1,1);
INSERT INTO PACIENTES(APELLIDO,NOMBRE,EMAIL,DNI,FECHA_INGRESO,DOMICILIO_ID,ODONTOLOGO_ID) VALUES('Perez','Micaela','mika@gmail.com','99999999','2021-07-06',2,1);


INSERT INTO ODONTOLOGOS(APELLIDO,NOMBRE,MATRICULA) VALUES('Ramirez','Juan','MP123');

INSERT INTO TURNOS (PACIENTE_ID,ODONTOLOGO_ID,FECHA_HORA) VALUES(1,1,'2019-07-09');
